stages:
  - packaging
  - build_docker_image
default:
  image: maven:3.8.3-openjdk-17

variables:
  MAVEN_OPTS : "Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
run unit test and package:
  inherit:
    default: true
    variables: true
  stage: packaging
  script:
    - mvn clean package -Dmaven.test.skip
  artifacts:
    paths:
      - target/*.jar
  cache:
    paths:
      - .m2/repository

  #build docker image from Dockerfile
build docker image:
  image: docker:latest
  stage: build_docker_image
  inherit:
    default: false
    variables: false
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_USER/impot:1.0 .
    - docker save $DOCKER_USER/impot > impot
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push $DOCKER_USER/impot:1.0
  artifacts:
    paths:
      - impot
  when: manual